apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: app
  name: tenant-details
  namespace: tenant-details
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-details
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant-details
    spec:
      containers:
      - image: karankapoor/tenant-details:3f9fd60993b03a354d165606970b127c6deb98e3
        name: tenant-details
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: tenant-identity
        resources:
          limits:
            memory: "32Mi"
            cpu: "250m"
