apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: app
  name: tenant-details
  namespace: k-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-details
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant-details
    spec:
      containers:
      - image: karankapoor/multi-tenant:1a8fcdf22b0e6af9c05d9424cbd0cd0d620149fd
        name: tenant-details
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: tenant-identity
