apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: app
  name: k-details
  namespace: k-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k-details
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k-details
    spec:
      containers:
      - image: karankapoor/multi-tenant:c11423bc4bb27a28e325b816372992b467043d95
        name: k-details
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: k-identity
